- pipeline.id: syslog_pipeline
  path.config: "/usr/share/logstash/pipeline/filter-test-syslog.conf"
  queue.type: persisted
#- pipeline.id: cloudwatch_logs
#  path.config: "/usr/share/logstash/pipeline/cloudWatch.conf"
#  queue.type: persisted

