- pipeline.id: test_pipeline
  path.config: "/usr/share/logstash/pipeline/test-filebeat.conf"
  queue.type: ${GUC_PERSISTENT_QUEUE_TYPE:memory}
  pipeline.ecs_compatibility: disabled
- pipeline.id: customer_pipeline
  path.config: "${GI_PIPELINE_DIR:/usr/share/logstash/customer/pipeline/}"
  queue.type: ${GUC_PERSISTENT_QUEUE_TYPE:memory}
  pipeline.ecs_compatibility: disabled